version : '3'

services : 
  vuejs:
    build:
      context: ./node
      dockerfile: DockerFile
    image: test/vuejs:1.0.0
    volumes: 
      - <path/to/cart-client/dir>:/var/www/html
      - node_modules:/var/www/html/node_modules
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    networks:
      - appnet
    command: npm run dev 

volumes:
  node_modules: 

networks: 
  appnet: